# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [296]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [297]:
# your code here
print(np.__version__)

1.22.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [298]:
# Method 1
# a = np.ndarray([[0,1], ['a','b','c'], ['v', 'w', 'x', 'y', 'z']])
a = np.random.random((2,3,5))
print(a)

[[[0.0246875  0.45616473 0.50643232 0.82962145 0.72484979]
  [0.66642861 0.2122142  0.54133412 0.35047095 0.18806973]
  [0.75681211 0.62706167 0.59500774 0.11992578 0.03496117]]

 [[0.12990695 0.85776264 0.37456959 0.26312471 0.4238787 ]
  [0.94847129 0.14746175 0.83178829 0.62907627 0.33028427]
  [0.7741879  0.13563409 0.28849253 0.41013443 0.79586644]]]


In [299]:
# Method 2
# Method 3
a = np.arange(30).reshape(2,3,5)
a

print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [300]:
# Method 3
rg = np.random.default_rng(1)
a= rg.random((2,3,5))
print(a)

[[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
  [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
  [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]]

 [[0.45349789 0.1340417  0.40311299 0.20345524 0.26231334]
  [0.75036467 0.28040876 0.48519097 0.9807372  0.96165719]
  [0.72478994 0.54122686 0.2768912  0.16065201 0.96992541]]]


#### 4. Print *a*.


In [301]:
# your code here
print(a)

[[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
  [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
  [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]]

 [[0.45349789 0.1340417  0.40311299 0.20345524 0.26231334]
  [0.75036467 0.28040876 0.48519097 0.9807372  0.96165719]
  [0.72478994 0.54122686 0.2768912  0.16065201 0.96992541]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [302]:
# your code here
b = np.ones(shape=(5,2,3), dtype=int)


#### 6. Print *b*.


In [303]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [304]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [305]:
# your answer here
z = a + b
print(z)
#operands could not be broadcast together with shapes (2,3,5) (5,2,3)
#I'm guessing structures (shapes) are not the same

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [ ]:
# your code here

c = np.transpose(b, axes=(1,2,0))
c.shape
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [ ]:
# your code/answer here
print(np.shape(a))
print(np.shape(b))
d = a + c
print(d)

# it works because both matrices have the same shape now 

(2, 3, 5)
(5, 2, 3)
[[[1.51182162 1.9504637  1.14415961 1.94864945 1.31183145]
  [1.42332645 1.82770259 1.40919914 1.54959369 1.02755911]
  [1.75351311 1.53814331 1.32973172 1.7884287  1.30319483]]

 [[1.45349789 1.1340417  1.40311299 1.20345524 1.26231334]
  [1.75036467 1.28040876 1.48519097 1.9807372  1.96165719]
  [1.72478994 1.54122686 1.2768912  1.16065201 1.96992541]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [ ]:
# your code/answer here
print(a)
print(d)

[[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
  [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
  [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]]

 [[0.45349789 0.1340417  0.40311299 0.20345524 0.26231334]
  [0.75036467 0.28040876 0.48519097 0.9807372  0.96165719]
  [0.72478994 0.54122686 0.2768912  0.16065201 0.96992541]]]
[[[1.51182162 1.9504637  1.14415961 1.94864945 1.31183145]
  [1.42332645 1.82770259 1.40919914 1.54959369 1.02755911]
  [1.75351311 1.53814331 1.32973172 1.7884287  1.30319483]]

 [[1.45349789 1.1340417  1.40311299 1.20345524 1.26231334]
  [1.75036467 1.28040876 1.48519097 1.9807372  1.96165719]
  [1.72478994 1.54122686 1.2768912  1.16065201 1.96992541]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [ ]:
# your code here
e = a * c
e

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
e
a

array([[[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145],
        [0.42332645, 0.82770259, 0.40919914, 0.54959369, 0.02755911],
        [0.75351311, 0.53814331, 0.32973172, 0.7884287 , 0.30319483]],

       [[0.45349789, 0.1340417 , 0.40311299, 0.20345524, 0.26231334],
        [0.75036467, 0.28040876, 0.48519097, 0.9807372 , 0.96165719],
        [0.72478994, 0.54122686, 0.2768912 , 0.16065201, 0.96992541]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [ ]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [ ]:
# your code here
f = np.empty((2,3,5))
print(f)
print(d.shape)

[[[1400.51182162 1400.9504637  1400.14415961 1400.94864945 1400.31183145]
  [1400.42332645 1400.82770259 1400.40919914 1400.54959369 1400.02755911]
  [1400.75351311 1400.53814331 1400.32973172 1400.7884287  1400.30319483]]

 [[1400.45349789 1400.1340417  1400.40311299 1400.20345524 1400.26231334]
  [1400.75036467 1400.28040876 1400.48519097 1400.9807372  1400.96165719]
  [1400.72478994 1400.54122686 1400.2768912  1400.16065201 1400.96992541]]]
(2, 3, 5)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:
f=[]
# your code here
for x in np.nditer(d):
        if d_min < x < d_mean:
                f += [25]
        if d_mean < x < d_max:
                f += [75]
        if x == d_mean:
                f += [50]
        if x == d_min:
                f += [0]
        if x == d_max:
                f += [100]
f = np.reshape(f, d.shape)
print(f)

[[[ 25  75  25  75  25]
  [ 25  75  25  75   0]
  [ 75  75  25  75  25]]

 [[ 25  25  25  25  25]
  [ 75  25  25 100  75]
  [ 75  75  25  25  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [306]:
# your code here
d
f

array([[[ 25,  75,  25,  75,  25],
        [ 25,  75,  25,  75,   0],
        [ 75,  75,  25,  75,  25]],

       [[ 25,  25,  25,  25,  25],
        [ 75,  25,  25, 100,  75],
        [ 75,  75,  25,  25,  75]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [307]:
# your code here